services:
  inventory-db:
    image: postgres:18
    container_name: inventory-postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventory-service
      TZ: Asia/Kolkata
    volumes:
      - ./inventory-postgres:/var/lib/postgresql